/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/myweb/': RouteRecordInfo<'/myweb/', '/myweb', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/开始/myFirstPage': RouteRecordInfo<'/posts/开始/myFirstPage', '/posts/开始/myFirstPage', Record<never, never>, Record<never, never>>,
    '/posts/Blender/BlenderStart': RouteRecordInfo<'/posts/Blender/BlenderStart', '/posts/Blender/BlenderStart', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/Houdini/HoudiniRBD': RouteRecordInfo<'/posts/Houdini/HoudiniRBD', '/posts/Houdini/HoudiniRBD', Record<never, never>, Record<never, never>>,
    '/posts/Houdini/PDGLInkUnity': RouteRecordInfo<'/posts/Houdini/PDGLInkUnity', '/posts/Houdini/PDGLInkUnity', Record<never, never>, Record<never, never>>,
    '/posts/Houdini/PDGLinkUnity2': RouteRecordInfo<'/posts/Houdini/PDGLinkUnity2', '/posts/Houdini/PDGLinkUnity2', Record<never, never>, Record<never, never>>,
    '/posts/MarkDown/MarkDowmHelp': RouteRecordInfo<'/posts/MarkDown/MarkDowmHelp', '/posts/MarkDown/MarkDowmHelp', Record<never, never>, Record<never, never>>,
    '/posts/Music/MusicalNotation': RouteRecordInfo<'/posts/Music/MusicalNotation', '/posts/Music/MusicalNotation', Record<never, never>, Record<never, never>>,
    '/posts/MyGame/First': RouteRecordInfo<'/posts/MyGame/First', '/posts/MyGame/First', Record<never, never>, Record<never, never>>,
    '/posts/MyGame/TWO_TerrainforGaia': RouteRecordInfo<'/posts/MyGame/TWO_TerrainforGaia', '/posts/MyGame/TWO_TerrainforGaia', Record<never, never>, Record<never, never>>,
    '/posts/suibi/2023_09_04': RouteRecordInfo<'/posts/suibi/2023_09_04', '/posts/suibi/2023_09_04', Record<never, never>, Record<never, never>>,
    '/posts/suibi/2023_10_22': RouteRecordInfo<'/posts/suibi/2023_10_22', '/posts/suibi/2023_10_22', Record<never, never>, Record<never, never>>,
    '/posts/suibi/LongPageOnTsStudio': RouteRecordInfo<'/posts/suibi/LongPageOnTsStudio', '/posts/suibi/LongPageOnTsStudio', Record<never, never>, Record<never, never>>,
    '/posts/Unity/SRP1': RouteRecordInfo<'/posts/Unity/SRP1', '/posts/Unity/SRP1', Record<never, never>, Record<never, never>>,
    '/posts/Unity/UnityShader/ToonHightQulitySkinShader': RouteRecordInfo<'/posts/Unity/UnityShader/ToonHightQulitySkinShader', '/posts/Unity/UnityShader/ToonHightQulitySkinShader', Record<never, never>, Record<never, never>>,
    '/posts/Unity/UnityShader/UnityCharToonShaderPreview': RouteRecordInfo<'/posts/Unity/UnityShader/UnityCharToonShaderPreview', '/posts/Unity/UnityShader/UnityCharToonShaderPreview', Record<never, never>, Record<never, never>>,
    '/posts/Unity/UnityShader/ZhanShuangRendringPBRMixer': RouteRecordInfo<'/posts/Unity/UnityShader/ZhanShuangRendringPBRMixer', '/posts/Unity/UnityShader/ZhanShuangRendringPBRMixer', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
